### ISSUE TITLE
issue with rotate function

### ISSUE THREAD

**Issue by yashwanth850** [PaulScotti/inverted_encoding#1]
def rotate(l,dist):
    # This is identical but faster than np.roll() for larger matrices 
    l=l.tolist()
    for i,d in enumerate(dist):
        ll = l[i]
        for _ in range(d):
            ll.append(ll.pop(0))
    return np.array(l)
    
Why is l[i] not being updated after rotation? I think l is being returned as it is.  Can you please clarify

**Comment by PaulScotti** [comment]
The function works right? Are you confused about how it works?

Even though l is being returned, it is modified due to ll

It's the same reason that variable "a" in the below code gets changed despite "a" never being modified directly.

In Python, setting a variable actually sets a reference to the variable.

```
a = [1]
b = a
b.append(2)
print(a) # outputs [1,2]
```
